//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_enquiry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbs_studentEntities : DbContext
    {
        public dbs_studentEntities()
            : base("name=dbs_studentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<enquiry> enquiries { get; set; }
        public virtual DbSet<todaylist> todaylists { get; set; }
    }
}
