//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_enquiry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todaylist
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TOTAL_LEAD { get; set; }
        public string TOTAL_CALLS { get; set; }
        public string GENUINE { get; set; }
        public string FAKE { get; set; }
        public string INTERESTED { get; set; }
        public string IN_PROGRESS { get; set; }
        public string CONVERTED { get; set; }
        public string RECEIVECALLS { get; set; }
        public string UNRECEIVECALLS { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    }
}
